### ISSUE TITLE
Burger menu is golden, sections should instead be golden

### ISSUE THREAD

**Issue by bee-san** [LivHackSoc/LivHackSoc.github.io#10]
Caused by a CSS issue in pull request #9

the exact code is:

```
#navigation-bar {
    color: #f7b733;
}
```

This makes the burger menu golden

![screenshot_2018-06-02 liverpool university hackathon society](https://user-images.githubusercontent.com/10378052/40877265-a1760fcc-6675-11e8-9fed-fbd8247eafbc.png)

Also the text is blue, it should be golden.

This seems like a simple CSS bug. I'm writing this as an issue so someone new to GitHub can fix it easily.

**Comment by Thepnathi** [comment]
Yeah good idea. I will leave it to them.

**Comment by MJHarding** [comment]
Seems to me like Stylesheet ordering gives bootstrap priority over our own. Not fixed it myself though.

**Comment by bee-san** [comment]
@MJHarding that is caused by the importing of Bootstrap's CSS being physically below the other CSS sheets. If you move Bootstrap to be above the others then our CSS will be executed and favoured instead of bootstrap will solve when i have other things to commit :)

**Comment by Thepnathi** [comment]
The issue is fixed.
