### ISSUE TITLE
Write JS to grab the newest event from a FB feed

### ISSUE THREAD

**Issue by bee-san** [LivHackSoc/LivHackSoc.github.io#15]
We have a facebook page. We can create events for this facebook page. I assume that somehow these events will be in an RSS feed (you'll need to double-check). Can you write some JS that grabs the closet event to the current date and returns that in a <p> with a hyperlink at all?

I'm writing an FAQ for our website and I want one of the questions to be:
"When is your next event?"
and I want the JS to automatically pick our next event

Our (FB page)[https://www.facebook.com/HackSoc-Liverpool-1349455425160000/]
(a test event you can use)[https://www.facebook.com/events/1673827002693969/]

**Comment by bee-san** [comment]
Facebook no longer lets you retrieve a list of events, [blog post here](https://developers.facebook.com/blog/post/2018/04/04/facebook-api-platform-product-changes)

I'll keep looking into this.

**Comment by mshaugh** [comment]
Migrated to [Graph API](https://developers.facebook.com/docs/graph-api/reference/page/events/)

**Comment by bee-san** [comment]
We can't request access to the Graph APi "at this time", so will temporarily close this issue.
