### ISSUE TITLE
Add functionality to email form

### ISSUE THREAD

**Issue by robertszafa** [LivHackSoc/LivHackSoc.github.io#16]
If anyone knows the preferred way to send out emails from a website, please let me know. I will make some research on my own as well.

**Comment by robertszafa** [comment]
I experimented with [Yinzo/PostMail ](https://github.com/Yinzo/PostMail#eng_title) and got it to work. However, this is not a popular way to do it and probably not the best.

**Comment by bee-san** [comment]
Is there anyway we can embed something? I have a form on my Jekyll site hosted on github pages that accepts emails being added to an email list. Scroll to bottom here: http://skerritt.tech/university/compiler/

**Comment by mshaugh** [comment]
[Formspree](https://formspree.io/) seems to be the go-to for Jekyll.

**Comment by robertszafa** [comment]
I will start working on it now

**Comment by robertszafa** [comment]
The email form is fully functional now. @mshaugh thanks for the suggestion, I implemented Formspree.
