### ISSUE TITLE
Find a way to generate a nice mindmap for the "about us" section.

### ISSUE THREAD

**Issue by bee-san** [LivHackSoc/LivHackSoc.github.io#18]
@Thepnathi & I were discussing that a mindmap of what we do is more interesting and creative than a simple paragraph description.

I want the mindmap to sort of float, look like it exists and is interactive. I don't really want it to be a simple image just pasted onto the screen.

The task here is to find some library or something that can generate an interesting mindmap that we can insert into our website.

Once we have found a library the next task is to create the mindmap

**Comment by mshaugh** [comment]
[D3.js](https://d3js.org/) and [Processing.js](http://processingjs.org/) are two options
