### ISSUE TITLE
Put the HackSoc logo as a favicon

### ISSUE THREAD

**Issue by bee-san** [LivHackSoc/LivHackSoc.github.io#4]
Not sure if it needs to be scaled down but someone with the PNG version of the logo put it the root folder as favicon.ico

GitHub pages will automatically set it as the favicon

**Comment by Thepnathi** [comment]
Someone else can work on this. Same goes for MLH logo. I will put all of the favicon folder in the project.

**Comment by bee-san** [comment]
This is fixed. An issue occurs whereby if you've been on the site before the favicon will not load.
See [this](https://stackoverflow.com/questions/2208933/how-do-i-force-a-favicon-refresh?rq=1) for more information.
